sudo: required
language: node_js
node_js:
  - "6.13.0"

notifications:
  email:
    on_success: never
    on_failure: always
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_script:
  - npm install
script:
  - npm run build
deploy:
  provider: npm
  email: $USER_EMAL
  api_key: $NPM_KEY
